[tool.poetry]
name = "udp"
version = "0.1.0"
description = "UDP examples"
authors = []

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.dependencies]
python = "^3.9"
asyncudp = "^0.7.1"
